"""Runtime provenance — bind source, dependency lock, bridge artifact and target runtime.
Wing: code | Topic: mp0-t00-reproducibility | Updated: 2026-09-10 23:24
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import platform
import subprocess
import sys
import tomllib
from collections.abc import Iterable, Mapping
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

_SOURCE_SUFFIXES = {".py", ".cs", ".csproj", ".props", ".targets", ".json", ".toml"}
_EXCLUDED_SOURCE_PARTS = {".git", ".deps", ".venv", "__pycache__", "artifacts", "bin", "obj"}


def _sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def canonical_lock_path(repo_root: str | Path) -> Path:
    """Select the one platform lock generated by the canonical pip-lock workflow."""
    root = Path(repo_root).resolve()
    if sys.platform == "win32":
        return root / "pylock.windows.toml"
    if sys.platform.startswith("linux"):
        return root / "pylock.linux.toml"
    raise RuntimeError(f"unsupported lock platform: {sys.platform}")


def read_lock_packages(lock_path: str | Path) -> dict[str, str]:
    """Return exact package versions from a PEP 751 pylock file."""
    path = Path(lock_path)
    data = tomllib.loads(path.read_text(encoding="utf-8"))
    packages: dict[str, str] = {}
    for package in data.get("packages", []):
        name = str(package.get("name", "")).strip().lower()
        version = package.get("version")
        if name and version is not None:
            packages[name] = str(version)
    return dict(sorted(packages.items()))


def _iter_source_files(repo_root: Path, roots: Iterable[Path]) -> list[Path]:
    files: list[Path] = []
    for relative in roots:
        candidate = repo_root / relative
        if candidate.is_file():
            files.append(candidate)
            continue
        if not candidate.is_dir():
            continue
        for path in candidate.rglob("*"):
            if not path.is_file():
                continue
            rel = path.relative_to(repo_root)
            if any(part in _EXCLUDED_SOURCE_PARTS for part in rel.parts):
                continue
            if path.suffix.lower() in _SOURCE_SUFFIXES:
                files.append(path)
    return sorted(set(files), key=lambda item: item.relative_to(repo_root).as_posix())


def hash_source_tree(repo_root: str | Path, roots: Iterable[Path]) -> str:
    """Hash relative paths plus file bytes for the selected source roots."""
    root = Path(repo_root).resolve()
    digest = hashlib.sha256()
    for path in _iter_source_files(root, roots):
        relative = path.relative_to(root).as_posix().encode("utf-8")
        digest.update(relative)
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()


def _git(repo_root: Path, *args: str) -> bytes:
    result = subprocess.run(
        ["git", *args],
        cwd=repo_root,
        check=True,
        capture_output=True,
    )
    return result.stdout


def _autocad_process_state() -> dict[str, Any]:
    if os.name != "nt":
        return {
            "process_present": None,
            "pid": None,
            "session": None,
            "observation": "not_windows",
        }
    result = subprocess.run(
        ["tasklist", "/FI", "IMAGENAME eq acad.exe", "/FO", "CSV", "/NH"],
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    line = result.stdout.strip()
    if not line or line.upper().startswith("INFO:"):
        return {
            "process_present": False,
            "pid": None,
            "session": None,
            "observation": "tasklist",
        }
    try:
        import csv

        row = next(csv.reader([line]))
        pid = int(row[1]) if len(row) > 1 and row[1].isdigit() else None
        session = row[3] if len(row) > 3 else None
    except Exception:
        pid = None
        session = None
    return {
        "process_present": True,
        "pid": pid,
        "session": session,
        "observation": "tasklist",
    }


def _relative_or_string(path: Path, root: Path) -> str:
    try:
        return path.resolve().relative_to(root.resolve()).as_posix()
    except ValueError:
        return str(path.resolve())


def build_runtime_manifest(
    repo_root: str | Path,
    *,
    lock_path: str | Path,
    dll_path: str | Path | None = None,
    autocad_target: str = "AutoCAD 2027 full / Windows x64 / COM 26.0",
) -> dict[str, Any]:
    """Build a deterministic provenance manifest for the current working source/runtime observation."""
    root = Path(repo_root).resolve()
    lock = Path(lock_path).resolve()
    status = _git(root, "status", "--porcelain=v1", "--untracked-files=all")
    diff = _git(root, "diff", "--binary", "HEAD", "--")
    head = _git(root, "rev-parse", "HEAD").decode("utf-8").strip()
    packages = read_lock_packages(lock)
    source_hash = hash_source_tree(
        root,
        (
            Path("src/cdt_autocad"),
            Path("native/CDT.AutoCAD.Bridge"),
            Path("pyproject.toml"),
            Path("pylock.windows.toml"),
            Path("pylock.linux.toml"),
        ),
    )

    bridge_path = Path(dll_path).resolve() if dll_path is not None else None
    bridge_present = bool(bridge_path and bridge_path.is_file())
    bridge_sha = _sha256_file(bridge_path) if bridge_present and bridge_path else None

    try:
        pyproject = tomllib.loads((root / "pyproject.toml").read_text(encoding="utf-8"))
        provider_version = str(pyproject["project"]["version"])
    except (KeyError, FileNotFoundError, tomllib.TOMLDecodeError):
        provider_version = "unknown"

    return {
        "schema_version": 1,
        "generated_at_utc": datetime.now(UTC).isoformat(),
        "git": {
            "head": head,
            "dirty": bool(status.strip()),
            "tracked_diff_sha256": _sha256_bytes(diff),
        },
        "source": {
            "tree_sha256": source_hash,
            "scope": [
                "src/cdt_autocad",
                "native/CDT.AutoCAD.Bridge",
                "pyproject.toml",
                "pylock.windows.toml",
                "pylock.linux.toml",
            ],
        },
        "provider": {
            "version": provider_version,
        },
        "dependency_lock": {
            "format": "PEP 751 pylock.toml",
            "path": _relative_or_string(lock, root),
            "sha256": _sha256_file(lock),
            "package_count": len(packages),
            "packages": packages,
        },
        "bridge_artifact": {
            "present": bridge_present,
            "path": _relative_or_string(bridge_path, root) if bridge_path else None,
            "sha256": bridge_sha,
        },
        "autocad": {
            "target": autocad_target,
            **_autocad_process_state(),
        },
        "runtime": {
            "python_version": platform.python_version(),
            "python_executable": sys.executable,
            "platform": platform.platform(),
            "machine": platform.machine(),
            "hostname": platform.node(),
        },
    }


_ACCEPTANCE_RESULTS = {"PASS", "FAIL", "BLOCKED_ENVIRONMENT", "REVIEW_PENDING"}


def build_acceptance_record(
    runtime_manifest: dict[str, Any],
    *,
    run_id: str,
    finding_ids: Iterable[str],
    contract_version: str,
    contract_hash: str,
    loaded_bridge_observation: Mapping[str, Any] | None,
    fixture_path: str | Path | None,
    exit_code: int | None,
    result: str,
    checks: Iterable[dict[str, Any]],
    remaining_uncertainty: Iterable[str],
) -> dict[str, Any]:
    """Build one evidence record from identities observed during the acceptance run."""
    normalized_run_id = str(run_id or "").strip()
    if not normalized_run_id:
        raise ValueError("run_id must not be empty")
    normalized_result = str(result or "").strip().upper()
    if normalized_result not in _ACCEPTANCE_RESULTS:
        raise ValueError(f"unsupported acceptance result: {result}")

    git_identity = dict(runtime_manifest.get("git") or {})
    source_identity = dict(runtime_manifest.get("source") or {})
    provider_identity = dict(runtime_manifest.get("provider") or {})
    candidate_bridge_identity = dict(runtime_manifest.get("bridge_artifact") or {})
    loaded_bridge_identity = dict(loaded_bridge_observation or {})
    if loaded_bridge_observation is None:
        loaded_bridge_identity = {
            "present": False,
            "path": None,
            "sha256": None,
            "observation": "not_observed",
        }
    elif loaded_bridge_identity.get("present"):
        bridge_sha = str(loaded_bridge_identity.get("sha256") or "").strip().lower()
        observation = str(loaded_bridge_identity.get("observation") or "").strip()
        if len(bridge_sha) != 64 or not observation:
            raise ValueError(
                "loaded_bridge_observation must include a runtime-observed sha256 and observation method"
            )
        loaded_bridge_identity["sha256"] = bridge_sha
    autocad_identity = dict(runtime_manifest.get("autocad") or {})
    runtime_identity = dict(runtime_manifest.get("runtime") or {})
    observed_at = runtime_manifest.get("generated_at_utc")
    if not observed_at:
        raise ValueError("runtime manifest must include generated_at_utc")

    fixture: dict[str, Any] | None = None
    if fixture_path is not None:
        resolved_fixture = Path(fixture_path).resolve()
        if not resolved_fixture.is_file():
            raise FileNotFoundError(f"acceptance fixture not found: {resolved_fixture}")
        fixture = {
            "path": str(resolved_fixture),
            "sha256": _sha256_file(resolved_fixture),
            "size": resolved_fixture.stat().st_size,
        }

    return {
        "schema_version": 1,
        "run_id": normalized_run_id,
        "finding_ids": [str(item) for item in finding_ids],
        "source_commit": git_identity.get("head"),
        "source_dirty": bool(git_identity.get("dirty")),
        "source_diff_sha256": git_identity.get("tracked_diff_sha256"),
        "source_tree_sha256": source_identity.get("tree_sha256"),
        "provider_version": provider_identity.get("version"),
        "contract_version": str(contract_version),
        "contract_hash": str(contract_hash),
        "environment": {
            "runtime_observed_at_utc": observed_at,
            "candidate_bridge_artifact": candidate_bridge_identity,
            "loaded_bridge": loaded_bridge_identity,
            "autocad_process": {
                "target": autocad_identity.get("target"),
                "process_present": autocad_identity.get("process_present"),
                "pid": autocad_identity.get("pid"),
                "session": autocad_identity.get("session"),
                "observation": autocad_identity.get("observation"),
            },
            "runtime": runtime_identity,
        },
        "fixture": fixture,
        "exit_code": int(exit_code) if exit_code is not None else None,
        "checks": [dict(check) for check in checks],
        "result": normalized_result,
        "remaining_uncertainty": [str(item) for item in remaining_uncertainty],
    }


def register_accepted_artifact(
    registry_path: str | Path,
    evidence_path: str | Path,
) -> dict[str, Any]:
    """Register PASS evidence only when that run already recorded its loaded bridge hash."""
    evidence_file = Path(evidence_path).resolve()
    record = json.loads(evidence_file.read_text(encoding="utf-8"))
    if record.get("result") != "PASS":
        raise ValueError("only PASS evidence can enter the accepted-artifact registry")

    run_id = str(record.get("run_id") or "").strip()
    if not run_id:
        raise ValueError("acceptance evidence must include run_id")
    environment = record.get("environment") or {}
    bridge = environment.get("loaded_bridge") or {}
    bridge_sha = str(bridge.get("sha256") or "").strip().lower()
    bridge_observation = str(bridge.get("observation") or "").strip()
    observed_at = environment.get("runtime_observed_at_utc")
    if (
        not bridge.get("present")
        or len(bridge_sha) != 64
        or not bridge_observation
        or bridge_observation == "not_observed"
        or not observed_at
    ):
        raise ValueError(
            "accepted evidence must contain the runtime-observed bridge hash; "
            "do not retroactively bind an old event to today's binary"
        )

    evidence_sha = _sha256_file(evidence_file)
    candidate = {
        "run_id": run_id,
        "evidence_path": str(evidence_file),
        "evidence_sha256": evidence_sha,
        "source_commit": record.get("source_commit"),
        "source_diff_sha256": record.get("source_diff_sha256"),
        "contract_version": record.get("contract_version"),
        "contract_hash": record.get("contract_hash"),
        "loaded_bridge_path": bridge.get("path"),
        "loaded_bridge_sha256": bridge_sha,
        "loaded_bridge_observation": bridge_observation,
        "runtime_observed_at_utc": observed_at,
    }

    registry_file = Path(registry_path).resolve()
    if registry_file.is_file():
        registry = json.loads(registry_file.read_text(encoding="utf-8"))
        if registry.get("schema_version") != 1 or not isinstance(registry.get("entries"), dict):
            raise ValueError("invalid accepted-artifact registry schema")
    else:
        registry = {"schema_version": 1, "entries": {}}

    existing = registry["entries"].get(run_id)
    if existing is not None:
        comparable = {key: existing.get(key) for key in candidate}
        if comparable != candidate:
            raise ValueError(f"conflicting accepted-artifact entry for run_id: {run_id}")
        return registry

    registry["entries"][run_id] = {
        **candidate,
        "registered_at_utc": datetime.now(UTC).isoformat(),
    }
    registry_file.parent.mkdir(parents=True, exist_ok=True)
    temporary = registry_file.with_name(f".{registry_file.name}.{os.getpid()}.tmp")
    try:
        temporary.write_text(
            json.dumps(registry, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
            newline="\n",
        )
        os.replace(temporary, registry_file)
    finally:
        if temporary.exists():
            temporary.unlink()
    return registry


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate a CDT-AutoCAD runtime provenance manifest")
    parser.add_argument("--repo", type=Path, default=Path.cwd())
    parser.add_argument("--lock", type=Path, help="PEP 751 lock; defaults to the current platform lock")
    parser.add_argument("--dll", type=Path)
    parser.add_argument(
        "--autocad-target",
        default="AutoCAD 2027 full / Windows x64 / COM 26.0",
    )
    parser.add_argument("--output", type=Path)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    repo = args.repo.resolve()
    if args.lock is None:
        lock = canonical_lock_path(repo)
    else:
        lock = args.lock if args.lock.is_absolute() else repo / args.lock
    dll = args.dll
    if dll is not None and not dll.is_absolute():
        dll = repo / dll
    manifest = build_runtime_manifest(
        repo,
        lock_path=lock,
        dll_path=dll,
        autocad_target=args.autocad_target,
    )
    rendered = json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    if args.output is None:
        sys.stdout.write(rendered)
    else:
        output = args.output if args.output.is_absolute() else repo / args.output
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(rendered, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
